### ISSUE TITLE
Renaming "master" to "main" according to Google's Respectful Language policy

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/color-fonts#47]
`github.com` gives us this advice:

Your members will have to manually update their local environments. We'll let them know when they visit the repository, or you can share these commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by rsheeter** [comment]
Did somebody *do* this already? - I'm seeing main

**Comment by anthrotype** [comment]
I think @felipesanches did for all googlefonts repos, is that right?
