### ISSUE TITLE
Generate a mini corpus for the Fuzzer from Noto & Samples

### ISSUE THREAD

**Issue by drott** [googlefonts/color-fonts#48]
For the FreeType COLRv1 fuzzer [pull request](https://github.com/freetype/freetype2-testing/pull/93), it's more effective when the samples are small. 

I selected the top high-paint-count glyphs from Noto, and generate fonts of three glyphs each using:

```
high_paint_count_glyphs = [ 3046, 2446, 198, 3225, 1420, 146, 212, 2551, 2389, 2388, 2649, 2729, 2458, 1197, 396, 400, 2379, 246, 403, 189, 177, 1600, 1160, 420, 2387, 405, 2789, 2788, 2787, 2750 ]

def chunks_of_five():
    chunksize = 3;
    for i in range(0, len(high_paint_count_glyphs), chunksize):
        yield high_paint_count_glyphs[i:i + chunksize]

source_font = "noto-glyf_colr_1.ttf"
for count, chunk in enumerate(chunks_of_five()):
    gids = ",".join([str(item) for item in chunk])
    print (f"pyftsubset {source_font} --gids={gids} --output-file=noto_complex_glyphs_colrv1_{str(count)}.ttf")
```

Then ran these subsetting steps. 

This gives me
```
$ ls -lha *complex*ttf
-rw-r----- 1 drott primarygroup 102K Feb 18 19:19 noto_complex_glyphs_colrv1_0.ttf
-rw-r----- 1 drott primarygroup  36K Feb 18 19:19 noto_complex_glyphs_colrv1_1.ttf
-rw-r----- 1 drott primarygroup  57K Feb 18 19:19 noto_complex_glyphs_colrv1_2.ttf
-rw-r----- 1 drott primarygroup  20K Feb 18 19:19 noto_complex_glyphs_colrv1_3.ttf
-rw-r----- 1 drott primarygroup  23K Feb 18 19:19 noto_complex_glyphs_colrv1_4.ttf
-rw-r----- 1 drott primarygroup  23K Feb 18 19:19 noto_complex_glyphs_colrv1_5.ttf
-rw-r----- 1 drott primarygroup  23K Feb 18 19:19 noto_complex_glyphs_colrv1_6.ttf
-rw-r----- 1 drott primarygroup  19K Feb 18 19:19 noto_complex_glyphs_colrv1_7.ttf
-rw-r----- 1 drott primarygroup  21K Feb 18 19:19 noto_complex_glyphs_colrv1_8.ttf
-rw-r----- 1 drott primarygroup  11K Feb 18 19:19 noto_complex_glyphs_colrv1_9.ttf
```

The high paint count glyphs I determined by drawing all glyph ids from the font through skia and keeping a paint counter while traversing the graph.

It would be helpful if we could have this fuzzer font generation step in one of the configs. I am not sure what's the easiest way to oupdate the high-paint-count info.

**Comment by anthrotype** [comment]
> I am not sure what's the easiest way to oupdate the high-paint-count info.

we may want to recompute that dynamically on the source font instead of hard-coding it in the script. FontTools Paint objects have a traverse method that take a callback, the latter can be used to take tally of the paints for each base color glyph.

**Comment by drott** [comment]
Yes, I think so too, it should be updated - in whichever way works best. I'd be very happy if you could help incorporate this step of generating the fuzzer ones into this color-fonts repo. That would give me time to focus on the fuzzer and the upcoming review of that. While we have no format changes, this is not high priority but will then be needed.
