### ISSUE TITLE
PaintSolid 0xFFFF?

### ISSUE THREAD

**Issue by ctrlcctrlv** [googlefonts/color-fonts#78]
You're going to have to forgive me, I have no idea who to complain to about this.

There seems to have been an oversight, at least in Chrome, regarding what happens when PalletteIndex = 65535 (0xFFFF). When I try to use it, as in this font, [brokenCOLR.zip](https://github.com/googlefonts/color-fonts/files/7404020/brokenCOLR.zip), I get this broken output:

![image](https://user-images.githubusercontent.com/838783/138579239-39de76b1-c793-466e-9d71-1432a3d10fa9.png)

Therefore, it seems, I will not be able to compile FRB American Cursive using COLRv1 tables at this time.

# TTX dumps

## broken

```xml
      <Paint index="8" Format="10"><!-- PaintGlyph -->
        <Paint Format="2"><!-- PaintSolid -->
          <PaletteIndex value="65535"/>
          <Alpha value="1.0"/>
        </Paint>
        <Glyph value="bar"/>
      </Paint>
```

## OK

```xml
    <ColorGlyph name="A">
      <layer colorID="0" name="A_guidelines"/>
      <layer colorID="1" name="A_xheight"/>
      <layer colorID="65535" name="A"/>
    </ColorGlyph>
```

**Comment by drott** [comment]
https://bugs.chromium.org/p/skia/issues/detail?id=12576 is now fixed, which means this should work in all cases where the FreeType backend is used for rendering. That's always the case for COLRv1, but COLRv0 on Mac is going through CoreText on supported OS versions, i.e. Mac OS >= 10.13, but I am planning to change that and always use FreeType for COLRv0 and COLRv1 on Mac.

**Comment by ctrlcctrlv** [comment]
Thank you, I compiled Chromium from source and confirmed the fix works.

![image](https://user-images.githubusercontent.com/838783/140594842-8bef13ae-c50d-4210-9dde-35c917e7eb58.png)
