### ISSUE TITLE
Flag for Georgia is broken

### ISSUE THREAD

**Issue by twardoch** [googlefonts/color-fonts#86]
The flag for Georgia, the country (GE.svg in Noto Emoji repo) should look like this: 

![image](https://user-images.githubusercontent.com/519108/144850224-67cddde1-201d-4a19-9284-e2bb93db0525.png)

But in the fonts here in color-fonts repo, both in "picosvg" and in "colr1" fonts, it looks like: 

<img width="1100" alt="scr- 2021-12-06 at 13 57 24" src="https://user-images.githubusercontent.com/519108/144850324-afd2d532-203e-4c7e-a1d8-4b16e967eb0a.png">

(in two independent renderers — I tested an in-house tool and I tested the picosvg font in Firefox)

**Comment by rsheeter** [comment]
Flag emojis are the best :D Thank you for the report; @anthrotype could I impose on you to peek at why GE.svg dislikes us?

**Comment by anthrotype** [comment]
Thanks Adam. I tried rebuilding the waved SVG flags using latest picosvg and it seems to fix the problem.

https://github.com/googlefonts/noto-emoji/pull/373

![image](https://user-images.githubusercontent.com/6939968/145065824-b7882947-118b-4596-9fbb-f4bb50a80af8.png)

The missing border (most visible around flags with white background) is a different issue that we need to add support for in our flag-waving tool.
